### PR TITLE
Added Android getAsset method

### PR DESCRIPTION
**Pull request by mt81**
Hi, I have added the getAsset method in order to fetch the assets bundled within the .apk.

### CODE REVIEW

**Comment by johanneslumpe** [comment]
Thanks! Would you mind refactoring the Javascript file so that the `readFile` and `readAsset` share common code? (which is 99%). I wonder if instead of always throwing on iOS, we should maybe try to read the file from the main application bundle instead since that's where assets are stored.

Thoughts on this?

cc @cjdell

**Comment by mt81** [comment]
Absolutely! I can refactor the two methods and read files from the main bundle on iOS. Would it make sense to change the method name to something more generic? I was thinking readPackageResource or something similar... (Not good with names 😿  AHAH)

**Comment by mt81** [comment]
it could also be a readFile option Eg. { fromAppBundle:bool }

**Comment by benvium** [comment]
This is covered by https://github.com/johanneslumpe/react-native-fs/pull/83 now, so I'm going to close this PR. Thanks for your contribution!

**Pull request closed without merging**
