### PR TITLE
Added Integration tests

### PR DESCRIPTION
**Pull request by agenthunt**
Hi,

I added some integration tests for the existing api. Let me know your comments.

Thanks,
Shailesh.

### CODE REVIEW

**Comment by johanneslumpe** [comment]
Thanks for the PR - checked out the tests, nice! I noticed that if I let a test fail on purpose, the test-runner never finishes. Have you encountered that behavior too?

**Comment by agenthunt** [comment]
I have noticed that if done() function is not called at the end of a test, it doesn't finish.

**Comment by johanneslumpe** [comment]
Ok, can you fix that then? :)

**Comment by agenthunt** [comment]
Sure, which test case was that you made it fail ?

**Comment by johanneslumpe** [comment]
I just changed the [value to compare to](https://github.com/johanneslumpe/react-native-fs/pull/5/files#diff-d5efcfd23472e6b30047120837211886R55) to a static value, in order to see what would happen if it failed. The test itself doesn't fail normally, but it would be nice to get this fixed anyway instead of having hanging tests on errors.

**Comment by agenthunt** [comment]
Thanks. Fixed that now. Realised that there was another error that " test message was not showing in Xcode". Fixed that as well.

**Comment by johanneslumpe** [comment]
Ok cool! Let me merge this in for now :)

**Comment by agenthunt** [comment]
Thanks!!!

**Comment by johanneslumpe** [comment]
No thank you :)

**Pull request merged**
