### PR TITLE
Update RNFSManager writeFile method to handle attributes.

### PR DESCRIPTION
**Pull request by K0rdan**
You can now append data to a file with the 'append' attribute.

### CODE REVIEW

**Comment by IjzerenHein** [comment]
This is awesome, just what I was looking for! 😀 Hope this gets accepted to the main branch quickly.
Are you planning on doing an Android implementation too?
👍 👍 👍

**Comment by johanneslumpe** [comment]
@K0rdan great! As @IjzerenHein mentioned, it would be great to get this in for Android too, so we have feature parity on this one :) Is that something you could look into?

**Comment by K0rdan** [comment]
Done !
Use the 'options' parameter was much more easier on Android as you can see in my update of the RNFSManager.java.

**Comment by IjzerenHein** [comment]
Sweet 😀 Awesome work @K0rdan !!

**Comment by cjdell** [comment]
@K0rdan @johanneslumpe I think we should accept however I'm wondering if this should be a separate `appendFile` method. It would be nice to make the library follow the same pattern as Node's `fs` module:

https://nodejs.org/api/fs.html#fs_fs_appendfile_file_data_options_callback

If no one objects I can make this change on top of this PR.

**Comment by IjzerenHein** [comment]
I totally agree with @johanneslumpe on trying the create API parity with nodejs 👍

**Comment by IjzerenHein** [comment]
Really looking forward to this new append feature. 👍  Do you have a target date when you want to release this?
Cheers

**Comment by cjdell** [comment]
@IjzerenHein Sorry `appendFile` has already been added, but I forgot to update the readme!

**Comment by IjzerenHein** [comment]
@cjdell Are you sure about that? The latest official version is 1.5.1 and was released 29 days ago. The pull request was created 13 days ago.

**Comment by cjdell** [comment]
@IjzerenHein Sorry, I meant it's on `master`. You can add the GitHub repo URL directly to your `package.json` if you need it now. I can't update the NPM package, only @johanneslumpe can do that.

**Comment by johanneslumpe** [comment]
@cjdell Is there anything else you want to merge in or should we cut a release?

**Pull request merged**
