### PR TITLE
Added progressDivider param to downloadFile method

### PR DESCRIPTION
**Pull request by kitolog**
Added `progressDivider` param to `downloadFile` method.
It helps filtering progressCallback events, emitting all events may occur performance issues on iOS and Android.

For example, if `progressDivider` = 10, you will receive only ten callbacks for this values of progress: 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100
Use it for performance issues.
If `progressDivider` = 1, you will receive all `progressCallback` calls, the default value is equal to 1.

### CODE REVIEW

**Comment by johanneslumpe** [comment]
@kitolog Thanks!

@grabbou @cjdell Thoughts?

@kitolog Please do not increment the package version in your PR. (apart from that: this would be a minor version change and not a patch, as it adds a feature)

**Comment by charliesbox** [comment]
@kitolog this would be awesome! on android performance goes way down while downloading files.

@johanneslumpe please accept this pull request :) !

**Comment by charlires** [comment]
This pull request is magic! solves a really bad performance issue I am having.

**Comment by johanneslumpe** [comment]
@charliesbox as per my comment above I am waiting to receive some feedback from @grabbou and @cjdell. Also please note that there is a pending change to not increment version number ;) Furthermore this PR needs to be rebased against master as there have been changes to`downloadFile`.

**Comment by cjdell** [comment]
@charliesbox @kitolog @johanneslumpe I'll try to get this merged in today at some point

**Comment by cjdell** [comment]
@charliesbox @kitolog @johanneslumpe Merged this in now. Tested it in my test app and it appears to be working :-)

**Comment by charliesbox** [comment]
@cjdell great! thanks guys! :)

**Comment by charliesbox** [comment]
@cjdell i can't make it work. im using 

```
let config = {
      fromUrl: fileUrl,
      toFile: mediaPath,
      begin: beginDownload,
      progress: progressCallback,
      progressDivider: 20,
      background: true
    };
RNFS.downloadFile(config)
```

but the progress callback is called like the progressdivider param didn't exist.

**Comment by cjdell** [comment]
@charliesbox This hasn't yet been published to NPM, are you referencing the GitHub repo directly inside package.json?

```
...
"react-native-fs": "git+https://github.com/johanneslumpe/react-native-fs.git"
...
```

**Comment by charliesbox** [comment]
@cjdell yeah, im using that. but i delete my node modules folder and reinstall and it worked again :) thanks for the help!

**Pull request merged**
