### PR TITLE
Bundle path information

### PR DESCRIPTION
**Pull request by MattFoley**
Hey, what do you think of this? It fixes some warnings, fixes some potential crashes, and adds the ability to fetch path information for an arbitrary NSBundle.

The crash fixes are the use of firstObject, `objectAtIndex:0` can crash, but `firstObject` will just return nil.

Force of habit, I changed the style slightly while I was fixing the warnings. Hopefully not too presumptuous? 

It's not totally ready, (I need to test it much more thoroughly) but I wanted to open this PR to give you a chance to look at it, before I wrapped it up

### CODE REVIEW

**Comment by johanneslumpe** [comment]
Hey! Cool sure :) But if you are making changes to for example method declarations make sure that you are sticking with it. Right now some methods are aligned with the`:` and others - albeit being spread out over multiple lines now - are not ;)

**Comment by MattFoley** [comment]
I go with aligning the colons myself on all normal ObjC methods, but with the `RCT_EXPORT_METHOD` macro, Xcode gets a little weird. Xcode wants to align those method declarations by the start of the word. 

That's the style that React Native has been using for `RCT_EXPORT_METHOD`, are you okay with that? Any other input? I tested this out yesterday, and it works pretty well, although I still need to confirm that it works with dynamic frameworks too.

**Comment by johanneslumpe** [comment]
@MattFoley no that is it :) Would you like me to give you collaborator status on this?

**Comment by MattFoley** [comment]
Sure :)

**Comment by johanneslumpe** [comment]
Ok you got it :)

**Comment by MattFoley** [comment]
Merging this @johanneslumpe I think you'd still need to be the one to push an update to npm if you wanted, right?

**Comment by johanneslumpe** [comment]
Just published with version 0.4.0!

**Comment by johanneslumpe** [comment]
Sorry for the long wait - I kind of lost track of this ;)

**Pull request merged**
