### PR TITLE
Return statusCode, headers for uploadFiles method

### PR DESCRIPTION
**Pull request by insraq**
1. Return statusCode, headers for uploadFiles method
2. Fix README for uploadFiles

### CODE REVIEW

**Comment by cjdell** [comment]
@insraq Looks good, tested and working, thanks for this :-)

**Comment by insraq** [comment]
Please note, this changes the response object in callback. So it's sort of a "breaking change"

**Comment by johanneslumpe** [comment]
@cjdell @insraq This is not just sort of a breaking change, it is definitely one ;) This could be a non-breaking change if we still kept the `response` entry in the dictionary. Thoughts?

**Comment by insraq** [comment]
@johanneslumpe Essentially you can. However, it would be confusing, as the old `response` is actually `body`. I will submit a new PR that includes `response` but won't mention it in the documentation. What do you think?

**Comment by cjdell** [comment]
@insraq @johanneslumpe Shame on me for not spotting this, I have returned the key to being `response` as there is no (really) good reason for this to change. I'm now also capturing this behaviour in my test app.

**Comment by cjdell** [comment]
@insraq @johanneslumpe Just realised in the docs that we're not actually describing the returned Promise object for some methods. I'll have to sort this out when I get another moment.

**Comment by insraq** [comment]
@cjdell Can you take a look at this PR? https://github.com/johanneslumpe/react-native-fs/pull/118/files

I think `statusCode` `headers` `body` is much clearer. than `statusCode` `headers` `response`. I keep `response` there to keep it compatible.

**Comment by cjdell** [comment]
@insraq Sorted, I've added them both in now. Did it manually as it was easier than dealing with the merge. :-)

**Comment by insraq** [comment]
@cjdell Great. Thanks a lot!

**Pull request merged**
