### PR TITLE
Update to load Bundles by their class name if not found in typical bundle path.

### PR DESCRIPTION
**Pull request by MattFoley**
This is mainly for dynamic/embedded frameworks. While they can be loaded as an NSBundle, they're not in the typical path.

### CODE REVIEW

**Comment by jnhuynh** [comment]
Looks good to me.

**Comment by MattFoley** [comment]
@johanneslumpe If you've got any feedback on this, I'll be happy to implement it, but I'm going to go ahead and merge this now since we're on radically different time zones.

**Comment by johanneslumpe** [comment]
Just published with version 0.4.0!

**Comment by MattFoley** [comment]
Cool! Will update to that. Been swamped myself.

**Pull request merged**
