### PR TITLE
Add copyFile

### PR DESCRIPTION
**Pull request by superandrew213**

### CODE REVIEW

**Comment by johanneslumpe** [comment]
Thanks! Sorry, was on vacation :) Why are you printing the stack trace before sending back the error on Android? Is that an Android best practice? Just wondering if there are any downsides to it in terms of performance (if it is not required)

**Comment by superandrew213** [comment]
@johanneslumpe no problem :) 

I just followed the same structure you had for the other methods.

**Comment by johanneslumpe** [comment]
@superandrew213 Ah ok - I didn't write any of the Android stuff. @cjdell can you shed some light on this?

**Comment by superandrew213** [comment]
@johanneslumpe all other methods follow this structure. Maybe we can merge this PR then later evaluate performance issues since we have to change all other methods. What do you think?

**Comment by johanneslumpe** [comment]
@superandrew213 sure, fine with me!

**Pull request merged**
